# Unordered list style
MD004:
  style: dash

# Ordered list item prefix
MD029:
  style: one

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# Code block style
MD046:
  style: fenced

# MD013/line-length
# - Line length
MD013:
  # Number of characters
  line_length: 120
  # Include tables
  tables: false

# MD024/no-duplicate-heading/no-duplicate-header
# - Multiple headings with the same content
MD024:
  allow_different_nesting: true
  siblings_only: true
