name: Test

on: [push, pull_request]

permissions:
  contents: read
  packages: read
  checks: write
  pull-requests: write

jobs:
  test:
    strategy:
      matrix:
        show-filename: [true, false]
        modes: [pr-comment, check, summary]
        file: [kubeconform-result-error.json, kubeconform-result-ok.json]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Kubeconform reporter test
        uses: ./
        with:
          file: ./__tests__/${{ matrix.file }}
          show-filename: ${{ matrix.show-filename }}
          modes: ${{ matrix.modes }}
  test-multi-mode:
    strategy:
      matrix:
        file: [ kubeconform-result-error.json, kubeconform-result-ok.json ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Kubeconform reporter test
        uses: ./
        with:
          file: ./__tests__/${{ matrix.file }}
          show-filename: false
          modes: |
            pr-comment
            check
  test-fail-on-error:
    strategy:
      matrix:
        file: [ kubeconform-result-error.json, kubeconform-result-ok.json ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Kubeconform reporter test
        uses: ./
        with:
          file: ./__tests__/${{ matrix.file }}
          show-filename: false
          modes: summary
          fail-on-error: true
        continue-on-error: true
